# Generated by Django 3.2.11 on 2022-02-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
