# Generated by Django 3.2.11 on 2022-01-30 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stores.store.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[stores.store.validators.capital_first_letter])),
                ('image', models.ImageField(upload_to='stores')),
                ('description', models.TextField(max_length=200)),
                ('location', models.TextField(max_length=80)),
                ('categories', models.ManyToManyField(to='common.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
