# Generated by Django 3.2.11 on 2022-01-30 21:33

from django.db import migrations, models
import stores.location.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=80, validators=[stores.location.validators.check_coordinates_valid]),
        ),
    ]
