# Generated by Django 3.2.11 on 2022-01-30 22:11

from django.db import migrations, models
import stores.location.validators
import stores.store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=80, validators=[stores.store.validators.check_coordinates_numbers, stores.location.validators.check_coordinates_valid]),
        ),
    ]
